image: ciscotestautomation/pyats:latest


stages:
  - build
  
build:
  stage: build
  script:
  - pyats run job ./pyats/remote_management_access/remote_manage_job.py --testbed-file ./pyats/devnet_testbed.yml