---
plugin: netbox
api_endpoint: http://192.168.1.191:8000/
token: '0123456789abcdef0123456789abcdef01234567'
validate_certs: false
config_context: true
group_by:
 - device_roles
 - platforms
compose:
 ansible_network_os: platform.slug
query_filters:
 - has_primary_ip: True
 - status: "staged"