---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    token: OTBlNDk4NTctMWMwZC00MzE1LWEwOWItYmJkNWU5MjAzZWNiODMzNDE1OTAtOGEz_PF84_0198f08a-3880-4871-b55e-4863ccf723d5
    room_id: Y2lzY29zcGFyazovL3VzL1JPT00vNTIxOWRiYTAtYWNiMC0xMWViLTgzYjctOTVlMTRhZTBhYTE3

  tasks:

     - name: Cisco Webex Teams - Text Message to a Room
       community.general.cisco_webex:
         recipient_type: roomId
         recipient_id: "{{ room_id }}"
         msg_type: text
         personal_token: "{{ token }}"
         msg: "The Baku Device Config Backup has COMPLETED \n http://192.168.1.191:8002/backups/"